;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Event.HitScan.Stop",NewTagName="Event.HitScan.End")
+GameplayTagList=(Tag="Cooldown.Damage",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Health.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.AxeSwing",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Projectile.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Projectile.Transform",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Projectile.TransformSpawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Activate",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="Gameplaycue.Dash.Activate",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Activate",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="Status.Health.Regen",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Staff",DevComment="")

